; Generated by AHK Script Builder - zoom
; Keep the ACTION comments if you want to reload this script into the builder.
CoordMode, Mouse, Screen
SetTitleMatchMode, 2

; Hotkey to run the sequence: ^!z
^!z::
;ACTION:Run;Name=Run;Cmd=Zoom;Params=;Mode=Normal
    Run, Zoom
;ACTION:Sleep;Name=Sleep;MS=2000
    Sleep, 2000
;ACTION:Click;Name=Click;X=630;Y=430
    MouseMove, 630, 430
    Click
return